[project]
name = "html2yaml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NostraDavid", email = "55331731+NostraDavid@users.noreply.github.com" },
]
requires-python = ">=3.13"
dependencies = ["beautifulsoup4", "pyyaml"]

[project.scripts]
html2yaml = "html2yaml:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
