baseURL = 'http://thaumatorium.com/'
locale = 'en-us'
title = 'Thaumatorium'
subtitle = 'Where the Magic happens'
enableGitInfo = true

[security]
allowContent = ['^text/html$', '^text/markdown$']

[frontmatter]
lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[taxonomies]
author = 'NostraDavid'

[markup.goldmark.renderer]
unsafe = true
