baseURL = 'http://thaumatorium.com/'
languageCode = 'en-us'
title = 'Thaumatorium'
subtitle = 'Where the Magic happens'
enableGitInfo = true

[frontmatter]
lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[taxonomies]
author = 'NostraDavid'

[markup.goldmark.renderer]
unsafe = true
